// SPDX-License-Identifier: MIT

internal enum NativeOwnership: String {
    case owned = "OWNED"
    case borrowed = "BORROWED"
    case parentOwned = "PARENT_OWNED"
    case processGlobal = "PROCESS_GLOBAL"
    case managedValue = "MANAGED_VALUE"
}

internal struct NativeManifestEntry {
    /// The exported CNA C symbol.
    let symbol: String
    /// The `NativeFunctions` stored property that holds this route, and nothing else.
    let swiftField: String
    /// The route's own `@convention(c)` type. Every route has one of its own;
    /// no two routes share a type, so a swapped resolution is a named
    /// disagreement rather than a silently compatible alias.
    let routeType: String
    let cReturn: String
    let cParameters: [String]
    let ownership: NativeOwnership
    let resultLifetime: String
    let errorLifetime: String
    let callbackABI: String?
}

/// The reviewed function manifest. The corresponding Swift route types live
/// beside `NativeFunctions`, and tools/native_abi compares this metadata, the
/// Swift source and the Clang shim to canonical CNA headers.
///
/// `routeType` is mechanically derived from `symbol` — drop the `cna_` prefix,
/// capitalize each underscore-separated word, append `Route` — and the verifier
/// re-derives it rather than trusting the spelling here.
internal let nativeManifest: [NativeManifestEntry] = [
    .init(symbol: "cna_get_abi_version", swiftField: "getABIVersion", routeType: "GetAbiVersionRoute", cReturn: "uint32_t", cParameters: [], ownership: .processGlobal, resultLifetime: "value", errorLifetime: "none", callbackABI: nil),
    .init(symbol: "cna_error_get_last_message_size", swiftField: "errorMessageSize", routeType: "ErrorGetLastMessageSizeRoute", cReturn: "CNA_Result", cParameters: ["uint64_t* out_bytes"], ownership: .processGlobal, resultLifetime: "value", errorLifetime: "thread-local until next fallible call", callbackABI: nil),
    .init(symbol: "cna_error_copy_last_message", swiftField: "errorMessageCopy", routeType: "ErrorCopyLastMessageRoute", cReturn: "CNA_Result", cParameters: ["char* destination", "uint64_t capacity", "uint64_t* out_bytes"], ownership: .processGlobal, resultLifetime: "caller-owned copy", errorLifetime: "thread-local preserved", callbackABI: nil),
    .init(symbol: "cna_game_create", swiftField: "gameCreate", routeType: "GameCreateRoute", cReturn: "CNA_Result", cParameters: ["const CNA_GameCreateInfo* create_info", "CNA_Handle* out_game"], ownership: .owned, resultLifetime: "until cna_game_destroy", errorLifetime: "thread-local", callbackABI: "CNA_GameCallbacks"),
    .init(symbol: "cna_game_set_frame_hooks_ext", swiftField: "gameSetFrameHooks", routeType: "GameSetFrameHooksExtRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "const CNA_GameFrameHooks* hooks"], ownership: .borrowed, resultLifetime: "table copied", errorLifetime: "thread-local", callbackABI: "CNA_GameFrameHooks"),
    .init(symbol: "cna_game_run", swiftField: "gameRun", routeType: "GameRunRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_run_one_frame", swiftField: "gameRunOneFrame", routeType: "GameRunOneFrameRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_request_exit", swiftField: "gameRequestExit", routeType: "GameRequestExitRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_destroy", swiftField: "gameDestroy", routeType: "GameDestroyRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .owned, resultLifetime: "handle invalid after successful release", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_graphics_device", swiftField: "gameGetGraphicsDevice", routeType: "GameGetGraphicsDeviceRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Handle* out_graphics_device"], ownership: .borrowed, resultLifetime: "current callback only", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_create", swiftField: "graphicsManagerCreate", routeType: "GraphicsDeviceManagerCreateRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_GraphicsDeviceManagerHandle* out_manager"], ownership: .owned, resultLifetime: "until manager destroy", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_apply_changes", swiftField: "graphicsManagerApplyChanges", routeType: "GraphicsDeviceManagerApplyChangesRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_destroy", swiftField: "graphicsManagerDestroy", routeType: "GraphicsDeviceManagerDestroyRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager"], ownership: .owned, resultLifetime: "handle invalid after success", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_get_viewport", swiftField: "graphicsDeviceGetViewport", routeType: "GraphicsDeviceGetViewportRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "CNA_Viewport* out_viewport"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_clear_rgba", swiftField: "graphicsDeviceClearRGBA", routeType: "GraphicsDeviceClearRgbaRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "float r", "float g", "float b", "float a"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_texture2d_create_from_encoded_memory", swiftField: "textureCreateMemory", routeType: "Texture2dCreateFromEncodedMemoryRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "const uint8_t* encoded_data", "uint64_t encoded_byte_count", "const CNA_Texture2DDecodeInfo* decode_info", "CNA_Handle* out_texture"], ownership: .owned, resultLifetime: "game child until texture destroy", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_texture2d_get_info", swiftField: "textureGetInfo", routeType: "Texture2dGetInfoRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle texture", "CNA_Texture2DInfo* out_info"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_texture2d_destroy", swiftField: "textureDestroy", routeType: "Texture2dDestroyRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle texture"], ownership: .owned, resultLifetime: "handle invalid after success", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_sprite_batch_create", swiftField: "spriteBatchCreate", routeType: "SpriteBatchCreateRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "CNA_Handle* out_sprite_batch"], ownership: .owned, resultLifetime: "game child until batch destroy", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_sprite_batch_begin", swiftField: "spriteBatchBegin", routeType: "SpriteBatchBeginRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle sprite_batch", "const CNA_SpriteBatchBeginInfo* begin_info"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_sprite_batch_submit_scaled_many", swiftField: "spriteBatchSubmitScaled", routeType: "SpriteBatchSubmitScaledManyRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle sprite_batch", "const CNA_SpriteScaledCommand* commands", "uint64_t command_count"], ownership: .borrowed, resultLifetime: "commands copied", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_sprite_batch_end", swiftField: "spriteBatchEnd", routeType: "SpriteBatchEndRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle sprite_batch"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_sprite_batch_destroy", swiftField: "spriteBatchDestroy", routeType: "SpriteBatchDestroyRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle sprite_batch"], ownership: .owned, resultLifetime: "handle invalid after success", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_keyboard_get_state", swiftField: "keyboardGetState", routeType: "KeyboardGetStateRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_KeyboardState* out_state"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_keyboard_get_state_for_player", swiftField: "keyboardGetStateForPlayer", routeType: "KeyboardGetStateForPlayerRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_PlayerIndex player_index", "CNA_KeyboardState* out_state"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_gamepad_get_state", swiftField: "gamePadGetState", routeType: "GamepadGetStateRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_PlayerIndex player_index", "CNA_GamePadState* out_state"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_gamepad_get_state_with_dead_zone", swiftField: "gamePadGetStateWithDeadZone", routeType: "GamepadGetStateWithDeadZoneRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_PlayerIndex player_index", "CNA_GamePadDeadZone dead_zone_mode", "CNA_GamePadState* out_state"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_gamepad_get_capabilities", swiftField: "gamePadGetCapabilities", routeType: "GamepadGetCapabilitiesRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_PlayerIndex player_index", "CNA_GamePadCapabilities* out_capabilities"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_gamepad_set_vibration", swiftField: "gamePadSetVibration", routeType: "GamepadSetVibrationRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_PlayerIndex player_index", "float left_motor", "float right_motor", "CNA_Bool* out_applied"], ownership: .processGlobal, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_texture_get_info", swiftField: "textureCommonGetInfo", routeType: "TextureGetInfoRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle texture", "CNA_TextureInfo* out_info"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_render_target2d_create", swiftField: "renderTarget2DCreate", routeType: "RenderTarget2dCreateRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "const CNA_RenderTarget2DCreateInfo* create_info", "CNA_Handle* out_render_target"], ownership: .owned, resultLifetime: "game child until render target destroy", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_render_target_get_info", swiftField: "renderTargetGetInfo", routeType: "RenderTargetGetInfoRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle render_target", "CNA_RenderTargetInfo* out_info"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_render_target_destroy", swiftField: "renderTargetDestroy", routeType: "RenderTargetDestroyRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle render_target"], ownership: .owned, resultLifetime: "handle invalid after success; refused while bound", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_set_render_target2d", swiftField: "graphicsDeviceSetRenderTarget2D", routeType: "GraphicsDeviceSetRenderTarget2dRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle graphics_device", "CNA_Handle render_target"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_render_target_subscribe_content_lost", swiftField: "renderTargetSubscribeContentLost", routeType: "RenderTargetSubscribeContentLostRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle render_target", "CNA_RenderTargetContentLostCallback callback", "void* context", "CNA_RenderTargetEventRegistrationHandle* out_registration"], ownership: .owned, resultLifetime: "until unsubscribe or render target destroy", errorLifetime: "thread-local", callbackABI: "CNA_RenderTargetContentLostCallback"),
    .init(symbol: "cna_render_target_unsubscribe_content_lost", swiftField: "renderTargetUnsubscribeContentLost", routeType: "RenderTargetUnsubscribeContentLostRoute", cReturn: "CNA_Result", cParameters: ["CNA_RenderTargetEventRegistrationHandle registration"], ownership: .owned, resultLifetime: "registration invalid after success", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_tick", swiftField: "gameTick", routeType: "GameTickRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_suppress_draw", swiftField: "gameSuppressDraw", routeType: "GameSuppressDrawRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_reset_elapsed_time", swiftField: "gameResetElapsedTime", routeType: "GameResetElapsedTimeRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_is_active", swiftField: "gameGetIsActive", routeType: "GameGetIsActiveRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Bool* out_active"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_is_mouse_visible", swiftField: "gameGetIsMouseVisible", routeType: "GameGetIsMouseVisibleRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Bool* out_visible"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_set_is_mouse_visible", swiftField: "gameSetIsMouseVisible", routeType: "GameSetIsMouseVisibleRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Bool visible"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_is_fixed_time_step", swiftField: "gameGetIsFixedTimeStep", routeType: "GameGetIsFixedTimeStepRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Bool* out_fixed"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_set_is_fixed_time_step", swiftField: "gameSetIsFixedTimeStep", routeType: "GameSetIsFixedTimeStepRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_Bool fixed"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_target_elapsed_time_ticks", swiftField: "gameGetTargetElapsedTimeTicks", routeType: "GameGetTargetElapsedTimeTicksRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "int64_t* out_ticks"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_set_target_elapsed_time_ticks", swiftField: "gameSetTargetElapsedTimeTicks", routeType: "GameSetTargetElapsedTimeTicksRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "int64_t ticks"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_get_inactive_sleep_time_ticks", swiftField: "gameGetInactiveSleepTimeTicks", routeType: "GameGetInactiveSleepTimeTicksRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "int64_t* out_ticks"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_set_inactive_sleep_time_ticks", swiftField: "gameSetInactiveSleepTimeTicks", routeType: "GameSetInactiveSleepTimeTicksRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "int64_t ticks"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_game_subscribe", swiftField: "gameSubscribe", routeType: "GameSubscribeRoute", cReturn: "CNA_Result", cParameters: ["CNA_Handle game", "CNA_GameEvent event", "CNA_GameEventCallback callback", "void* context", "CNA_GameEventRegistrationHandle* out_registration"], ownership: .owned, resultLifetime: "until unsubscribe or game destroy", errorLifetime: "thread-local", callbackABI: "CNA_GameEventCallback"),
    .init(symbol: "cna_game_unsubscribe", swiftField: "gameUnsubscribe", routeType: "GameUnsubscribeRoute", cReturn: "CNA_Result", cParameters: ["CNA_GameEventRegistrationHandle registration"], ownership: .owned, resultLifetime: "registration invalid after success", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_create_device", swiftField: "graphicsManagerCreateDevice", routeType: "GraphicsDeviceManagerCreateDeviceRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_begin_draw", swiftField: "graphicsManagerBeginDraw", routeType: "GraphicsDeviceManagerBeginDrawRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager", "CNA_Bool* out_should_draw"], ownership: .managedValue, resultLifetime: "caller-owned value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_end_draw", swiftField: "graphicsManagerEndDraw", routeType: "GraphicsDeviceManagerEndDrawRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager"], ownership: .borrowed, resultLifetime: "value", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_get_graphics_device", swiftField: "graphicsManagerGetGraphicsDevice", routeType: "GraphicsDeviceManagerGetGraphicsDeviceRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager", "CNA_Handle* out_graphics_device"], ownership: .borrowed, resultLifetime: "current callback only", errorLifetime: "thread-local", callbackABI: nil),
    .init(symbol: "cna_graphics_device_manager_subscribe", swiftField: "graphicsManagerSubscribe", routeType: "GraphicsDeviceManagerSubscribeRoute", cReturn: "CNA_Result", cParameters: ["CNA_GraphicsDeviceManagerHandle manager", "CNA_GraphicsDeviceManagerEvent event", "CNA_GameEventCallback callback", "void* context", "CNA_GameEventRegistrationHandle* out_registration"], ownership: .owned, resultLifetime: "until cna_game_unsubscribe or manager destroy", errorLifetime: "thread-local", callbackABI: "CNA_GameEventCallback"),
]
