// SPDX-License-Identifier: MIT

extension Microsoft.Xna.Framework.Color {
    private static func predefined(_ packedValue: UInt32) -> Self {
        Self(packedValue: packedValue)
    }

    public static var Transparent: Microsoft.Xna.Framework.Color { predefined(0x00000000) }
    public static var AliceBlue: Microsoft.Xna.Framework.Color { predefined(0xFFFFF8F0) }
    public static var AntiqueWhite: Microsoft.Xna.Framework.Color { predefined(0xFFD7EBFA) }
    public static var Aqua: Microsoft.Xna.Framework.Color { predefined(0xFFFFFF00) }
    public static var Aquamarine: Microsoft.Xna.Framework.Color { predefined(0xFFD4FF7F) }
    public static var Azure: Microsoft.Xna.Framework.Color { predefined(0xFFFFFFF0) }
    public static var Beige: Microsoft.Xna.Framework.Color { predefined(0xFFDCF5F5) }
    public static var Bisque: Microsoft.Xna.Framework.Color { predefined(0xFFC4E4FF) }
    public static var Black: Microsoft.Xna.Framework.Color { predefined(0xFF000000) }
    public static var BlanchedAlmond: Microsoft.Xna.Framework.Color { predefined(0xFFCDEBFF) }
    public static var Blue: Microsoft.Xna.Framework.Color { predefined(0xFFFF0000) }
    public static var BlueViolet: Microsoft.Xna.Framework.Color { predefined(0xFFE22B8A) }
    public static var Brown: Microsoft.Xna.Framework.Color { predefined(0xFF2A2AA5) }
    public static var BurlyWood: Microsoft.Xna.Framework.Color { predefined(0xFF87B8DE) }
    public static var CadetBlue: Microsoft.Xna.Framework.Color { predefined(0xFFA09E5F) }
    public static var Chartreuse: Microsoft.Xna.Framework.Color { predefined(0xFF00FF7F) }
    public static var Chocolate: Microsoft.Xna.Framework.Color { predefined(0xFF1E69D2) }
    public static var Coral: Microsoft.Xna.Framework.Color { predefined(0xFF507FFF) }
    public static var CornflowerBlue: Microsoft.Xna.Framework.Color { predefined(0xFFED9564) }
    public static var Cornsilk: Microsoft.Xna.Framework.Color { predefined(0xFFDCF8FF) }
    public static var Crimson: Microsoft.Xna.Framework.Color { predefined(0xFF3C14DC) }
    public static var Cyan: Microsoft.Xna.Framework.Color { predefined(0xFFFFFF00) }
    public static var DarkBlue: Microsoft.Xna.Framework.Color { predefined(0xFF8B0000) }
    public static var DarkCyan: Microsoft.Xna.Framework.Color { predefined(0xFF8B8B00) }
    public static var DarkGoldenrod: Microsoft.Xna.Framework.Color { predefined(0xFF0B86B8) }
    public static var DarkGray: Microsoft.Xna.Framework.Color { predefined(0xFFA9A9A9) }
    public static var DarkGreen: Microsoft.Xna.Framework.Color { predefined(0xFF006400) }
    public static var DarkKhaki: Microsoft.Xna.Framework.Color { predefined(0xFF6BB7BD) }
    public static var DarkMagenta: Microsoft.Xna.Framework.Color { predefined(0xFF8B008B) }
    public static var DarkOliveGreen: Microsoft.Xna.Framework.Color { predefined(0xFF2F6B55) }
    public static var DarkOrange: Microsoft.Xna.Framework.Color { predefined(0xFF008CFF) }
    public static var DarkOrchid: Microsoft.Xna.Framework.Color { predefined(0xFFCC3299) }
    public static var DarkRed: Microsoft.Xna.Framework.Color { predefined(0xFF00008B) }
    public static var DarkSalmon: Microsoft.Xna.Framework.Color { predefined(0xFF7A96E9) }
    public static var DarkSeaGreen: Microsoft.Xna.Framework.Color { predefined(0xFF8BBC8F) }
    public static var DarkSlateBlue: Microsoft.Xna.Framework.Color { predefined(0xFF8B3D48) }
    public static var DarkSlateGray: Microsoft.Xna.Framework.Color { predefined(0xFF4F4F2F) }
    public static var DarkTurquoise: Microsoft.Xna.Framework.Color { predefined(0xFFD1CE00) }
    public static var DarkViolet: Microsoft.Xna.Framework.Color { predefined(0xFFD30094) }
    public static var DeepPink: Microsoft.Xna.Framework.Color { predefined(0xFF9314FF) }
    public static var DeepSkyBlue: Microsoft.Xna.Framework.Color { predefined(0xFFFFBF00) }
    public static var DimGray: Microsoft.Xna.Framework.Color { predefined(0xFF696969) }
    public static var DodgerBlue: Microsoft.Xna.Framework.Color { predefined(0xFFFF901E) }
    public static var Firebrick: Microsoft.Xna.Framework.Color { predefined(0xFF2222B2) }
    public static var FloralWhite: Microsoft.Xna.Framework.Color { predefined(0xFFF0FAFF) }
    public static var ForestGreen: Microsoft.Xna.Framework.Color { predefined(0xFF228B22) }
    public static var Fuchsia: Microsoft.Xna.Framework.Color { predefined(0xFFFF00FF) }
    public static var Gainsboro: Microsoft.Xna.Framework.Color { predefined(0xFFDCDCDC) }
    public static var GhostWhite: Microsoft.Xna.Framework.Color { predefined(0xFFFFF8F8) }
    public static var Gold: Microsoft.Xna.Framework.Color { predefined(0xFF00D7FF) }
    public static var Goldenrod: Microsoft.Xna.Framework.Color { predefined(0xFF20A5DA) }
    public static var Gray: Microsoft.Xna.Framework.Color { predefined(0xFF808080) }
    public static var Green: Microsoft.Xna.Framework.Color { predefined(0xFF008000) }
    public static var GreenYellow: Microsoft.Xna.Framework.Color { predefined(0xFF2FFFAD) }
    public static var Honeydew: Microsoft.Xna.Framework.Color { predefined(0xFFF0FFF0) }
    public static var HotPink: Microsoft.Xna.Framework.Color { predefined(0xFFB469FF) }
    public static var IndianRed: Microsoft.Xna.Framework.Color { predefined(0xFF5C5CCD) }
    public static var Indigo: Microsoft.Xna.Framework.Color { predefined(0xFF82004B) }
    public static var Ivory: Microsoft.Xna.Framework.Color { predefined(0xFFF0FFFF) }
    public static var Khaki: Microsoft.Xna.Framework.Color { predefined(0xFF8CE6F0) }
    public static var Lavender: Microsoft.Xna.Framework.Color { predefined(0xFFFAE6E6) }
    public static var LavenderBlush: Microsoft.Xna.Framework.Color { predefined(0xFFF5F0FF) }
    public static var LawnGreen: Microsoft.Xna.Framework.Color { predefined(0xFF00FC7C) }
    public static var LemonChiffon: Microsoft.Xna.Framework.Color { predefined(0xFFCDFAFF) }
    public static var LightBlue: Microsoft.Xna.Framework.Color { predefined(0xFFE6D8AD) }
    public static var LightCoral: Microsoft.Xna.Framework.Color { predefined(0xFF8080F0) }
    public static var LightCyan: Microsoft.Xna.Framework.Color { predefined(0xFFFFFFE0) }
    public static var LightGoldenrodYellow: Microsoft.Xna.Framework.Color { predefined(0xFFD2FAFA) }
    public static var LightGreen: Microsoft.Xna.Framework.Color { predefined(0xFF90EE90) }
    public static var LightGray: Microsoft.Xna.Framework.Color { predefined(0xFFD3D3D3) }
    public static var LightPink: Microsoft.Xna.Framework.Color { predefined(0xFFC1B6FF) }
    public static var LightSalmon: Microsoft.Xna.Framework.Color { predefined(0xFF7AA0FF) }
    public static var LightSeaGreen: Microsoft.Xna.Framework.Color { predefined(0xFFAAB220) }
    public static var LightSkyBlue: Microsoft.Xna.Framework.Color { predefined(0xFFFACE87) }
    public static var LightSlateGray: Microsoft.Xna.Framework.Color { predefined(0xFF998877) }
    public static var LightSteelBlue: Microsoft.Xna.Framework.Color { predefined(0xFFDEC4B0) }
    public static var LightYellow: Microsoft.Xna.Framework.Color { predefined(0xFFE0FFFF) }
    public static var Lime: Microsoft.Xna.Framework.Color { predefined(0xFF00FF00) }
    public static var LimeGreen: Microsoft.Xna.Framework.Color { predefined(0xFF32CD32) }
    public static var Linen: Microsoft.Xna.Framework.Color { predefined(0xFFE6F0FA) }
    public static var Magenta: Microsoft.Xna.Framework.Color { predefined(0xFFFF00FF) }
    public static var Maroon: Microsoft.Xna.Framework.Color { predefined(0xFF000080) }
    public static var MediumAquamarine: Microsoft.Xna.Framework.Color { predefined(0xFFAACD66) }
    public static var MediumBlue: Microsoft.Xna.Framework.Color { predefined(0xFFCD0000) }
    public static var MediumOrchid: Microsoft.Xna.Framework.Color { predefined(0xFFD355BA) }
    public static var MediumPurple: Microsoft.Xna.Framework.Color { predefined(0xFFDB7093) }
    public static var MediumSeaGreen: Microsoft.Xna.Framework.Color { predefined(0xFF71B33C) }
    public static var MediumSlateBlue: Microsoft.Xna.Framework.Color { predefined(0xFFEE687B) }
    public static var MediumSpringGreen: Microsoft.Xna.Framework.Color { predefined(0xFF9AFA00) }
    public static var MediumTurquoise: Microsoft.Xna.Framework.Color { predefined(0xFFCCD148) }
    public static var MediumVioletRed: Microsoft.Xna.Framework.Color { predefined(0xFF8515C7) }
    public static var MidnightBlue: Microsoft.Xna.Framework.Color { predefined(0xFF701919) }
    public static var MintCream: Microsoft.Xna.Framework.Color { predefined(0xFFFAFFF5) }
    public static var MistyRose: Microsoft.Xna.Framework.Color { predefined(0xFFE1E4FF) }
    public static var Moccasin: Microsoft.Xna.Framework.Color { predefined(0xFFB5E4FF) }
    public static var NavajoWhite: Microsoft.Xna.Framework.Color { predefined(0xFFADDEFF) }
    public static var Navy: Microsoft.Xna.Framework.Color { predefined(0xFF800000) }
    public static var OldLace: Microsoft.Xna.Framework.Color { predefined(0xFFE6F5FD) }
    public static var Olive: Microsoft.Xna.Framework.Color { predefined(0xFF008080) }
    public static var OliveDrab: Microsoft.Xna.Framework.Color { predefined(0xFF238E6B) }
    public static var Orange: Microsoft.Xna.Framework.Color { predefined(0xFF00A5FF) }
    public static var OrangeRed: Microsoft.Xna.Framework.Color { predefined(0xFF0045FF) }
    public static var Orchid: Microsoft.Xna.Framework.Color { predefined(0xFFD670DA) }
    public static var PaleGoldenrod: Microsoft.Xna.Framework.Color { predefined(0xFFAAE8EE) }
    public static var PaleGreen: Microsoft.Xna.Framework.Color { predefined(0xFF98FB98) }
    public static var PaleTurquoise: Microsoft.Xna.Framework.Color { predefined(0xFFEEEEAF) }
    public static var PaleVioletRed: Microsoft.Xna.Framework.Color { predefined(0xFF9370DB) }
    public static var PapayaWhip: Microsoft.Xna.Framework.Color { predefined(0xFFD5EFFF) }
    public static var PeachPuff: Microsoft.Xna.Framework.Color { predefined(0xFFB9DAFF) }
    public static var Peru: Microsoft.Xna.Framework.Color { predefined(0xFF3F85CD) }
    public static var Pink: Microsoft.Xna.Framework.Color { predefined(0xFFCBC0FF) }
    public static var Plum: Microsoft.Xna.Framework.Color { predefined(0xFFDDA0DD) }
    public static var PowderBlue: Microsoft.Xna.Framework.Color { predefined(0xFFE6E0B0) }
    public static var Purple: Microsoft.Xna.Framework.Color { predefined(0xFF800080) }
    public static var Red: Microsoft.Xna.Framework.Color { predefined(0xFF0000FF) }
    public static var RosyBrown: Microsoft.Xna.Framework.Color { predefined(0xFF8F8FBC) }
    public static var RoyalBlue: Microsoft.Xna.Framework.Color { predefined(0xFFE16941) }
    public static var SaddleBrown: Microsoft.Xna.Framework.Color { predefined(0xFF13458B) }
    public static var Salmon: Microsoft.Xna.Framework.Color { predefined(0xFF7280FA) }
    public static var SandyBrown: Microsoft.Xna.Framework.Color { predefined(0xFF60A4F4) }
    public static var SeaGreen: Microsoft.Xna.Framework.Color { predefined(0xFF578B2E) }
    public static var SeaShell: Microsoft.Xna.Framework.Color { predefined(0xFFEEF5FF) }
    public static var Sienna: Microsoft.Xna.Framework.Color { predefined(0xFF2D52A0) }
    public static var Silver: Microsoft.Xna.Framework.Color { predefined(0xFFC0C0C0) }
    public static var SkyBlue: Microsoft.Xna.Framework.Color { predefined(0xFFEBCE87) }
    public static var SlateBlue: Microsoft.Xna.Framework.Color { predefined(0xFFCD5A6A) }
    public static var SlateGray: Microsoft.Xna.Framework.Color { predefined(0xFF908070) }
    public static var Snow: Microsoft.Xna.Framework.Color { predefined(0xFFFAFAFF) }
    public static var SpringGreen: Microsoft.Xna.Framework.Color { predefined(0xFF7FFF00) }
    public static var SteelBlue: Microsoft.Xna.Framework.Color { predefined(0xFFB48246) }
    public static var Tan: Microsoft.Xna.Framework.Color { predefined(0xFF8CB4D2) }
    public static var Teal: Microsoft.Xna.Framework.Color { predefined(0xFF808000) }
    public static var Thistle: Microsoft.Xna.Framework.Color { predefined(0xFFD8BFD8) }
    public static var Tomato: Microsoft.Xna.Framework.Color { predefined(0xFF4763FF) }
    public static var Turquoise: Microsoft.Xna.Framework.Color { predefined(0xFFD0E040) }
    public static var Violet: Microsoft.Xna.Framework.Color { predefined(0xFFEE82EE) }
    public static var Wheat: Microsoft.Xna.Framework.Color { predefined(0xFFB3DEF5) }
    public static var White: Microsoft.Xna.Framework.Color { predefined(0xFFFFFFFF) }
    public static var WhiteSmoke: Microsoft.Xna.Framework.Color { predefined(0xFFF5F5F5) }
    public static var Yellow: Microsoft.Xna.Framework.Color { predefined(0xFF00FFFF) }
    public static var YellowGreen: Microsoft.Xna.Framework.Color { predefined(0xFF32CD9A) }
}
