#!/usr/bin/env python3
"""Render docs/generated/runtime-capabilities.md from its machine-readable source.

The Markdown table used to be maintained by hand beside `runtime-capabilities.json`
and had drifted by seven rows before this generator existed. `--check` fails
when the rendered output differs from what is on disk, so the two cannot drift
again.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs/runtime-capabilities.json"
TARGET = ROOT / "docs/generated/runtime-capabilities.md"


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def sentence(text: str) -> str:
    text = cell(text)
    if not text:
        return text
    body = text[0].upper() + text[1:]
    return body if body.endswith(".") else body + "."


def render(document: dict) -> str:
    environment = document["qualifiedEnvironment"]
    lines = [
        "# Runtime capabilities",
        "",
        "<!-- Generated by tools/runtime_capabilities/render.py from",
        "     docs/runtime-capabilities.json. Do not edit by hand. -->",
        "",
        f'Qualified boundary: Swift {environment["swift"]}, `{environment["target"]}`,',
        f'{environment["platform"]}, canonical CNA C ABI {environment["cnaAbi"]}',
        f'(admitted window: {environment["cnaAbiAdmittedWindow"]}),',
        f'{environment["renderer"]} renderer, {environment["audio"]} audio.',
        "",
        f'CNA source revision `{environment["cnaSourceRevision"]}`, library SHA-256',
        f'`{environment["cnaLibrarySha256"]}`.',
        "",
        "| Operation | Status | Evidence |",
        "|---|---|---|",
    ]
    for capability in document["capabilities"]:
        lines.append(
            f'| {cell(capability["operation"])} '
            f'| {cell(capability["status"])} '
            f'| {sentence(capability["evidence"])} |'
        )
    lines += [
        "",
        f'{len(document["capabilities"])} operations. The machine-readable source is',
        "`docs/runtime-capabilities.json`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    rendered = render(document)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print("RUNTIME_CAPABILITIES_RENDER=STALE")
            return 1
        print(f"RUNTIME_CAPABILITIES_RENDER=CURRENT OPERATIONS={len(document['capabilities'])}")
        return 0
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"RUNTIME_CAPABILITIES_RENDER=WRITTEN OPERATIONS={len(document['capabilities'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
